spring:
  profiles:
    active: smart
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost/hr
    username=: cubix
    password: cubix
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
---
hr:
  smart:
    - limit: 10.0
      percent: 10
    - limit: 5.0
      percent: 5
    - limit: 2.5
      percent: 2
  jwtConfig:
    issuer: HrApp
    algorithm:
      type: HS384
      secret: mysecret
    duration: 120
---
server:
  error:
    include-message: always
